version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore:lts
    steps:
      - checkout
      - run:
          command: apt-get update zip
      - run:
          command: apt-get install zip
      - restore_cache:
          key: dependency-cache-{{ checksum "DataConverter.Net.csproj" }}
      - run:
          command: dotnet lambda package -o lambdaApp.zip -c Release -f netcoreapp1.0
      - save_cache:
          key: dependency-cache-{{ checksum "DataConverter.Net.csproj" }}
          paths:
            - ~/.nuget/packages
      - store_artifacts:
          path: ~/lambdaApp.zip
          destination: ""